### ISSUE TITLE
Better to a add a note/comment to inline the js in the head

### ISSUE THREAD

**Issue by tufandevrim** [GoogleChromeLabs/first-input-delay#14]
https://github.com/GoogleChromeLabs/first-input-delay/blob/e117bc890448b2b6afe09536694b83b1b1e20f0b/demo/index.html#L1

**Comment by samarpanda** [comment]
But its already mentioned in the [readme usage doc](https://github.com/GoogleChromeLabs/first-input-delay#usage) i.e 
>Since it's less than 400 bytes (gzipped), we recommended you inline it directly into your document <head> to avoid a blocking request.

**Comment by philipwalton** [comment]
Closed via b79ae924bd6ee51cd19fdfd32e8d670012330db3. I agree it's clear in the README but I suppose it can't hurt to add a second warning to the demo source.
