### ISSUE TITLE
Firebase Performance Monitoring integration instructions

### ISSUE THREAD

**Issue by Matan** [GoogleChromeLabs/first-input-delay#17]
👋 Is there a special trace that needs to be invoked/stopped when integrated with Firebase performance monitoring? The Firebase documentation says to follow the instructions on this repo, but the example callback is for Google Analytics and the "first input delay" metric on the firebase console remains unpopulated.

Thanks in advance!

**Comment by Matan** [comment]
Update! Values started populating now, just weird that this metric took multiple days to show up, whereas the other did after a few hours. 👍

**Comment by philipwalton** [comment]
Hmmm, that is weird, but I'm glad it's working now!

**Comment by draxvint** [comment]
Hi!

I am working on an Angular project hosted on Firebase and I want to mesure FID. Can you help me, how to implement this?

I installed this project with NPM and I added the js file to angular.json's scripts array.

But I don't know where to put the callback method and what to write to the body.

I use AngularFire to connect firebase and added the performance module to the project.

Thank you!

**Comment by philipwalton** [comment]
> I installed this project with NPM and I added the js file to angular.json's scripts array.

I wouldn't do this. As the instructions in the README say, this script should be inlined in the `<head>` of your page. It needs to be the first script executed on the page, and it shouldn't block rendering.

> But I don't know where to put the callback method and what to write to the body.

As far as I know, the Firebase performance monitoring code will call the callback for you. You don't need to do anything other than add the script to the page.
