### ISSUE TITLE
intermittent erroneous (epoch time) values on certain browsers

### ISSUE THREAD

**Issue by stevesouders** [GoogleChromeLabs/first-input-delay#4]
We deployed this and got erroneous values that look like epoch times. This happened on more than 1% of real users across a wide variety of browsers. Some of the browsers were old (Firefox 45) but Safari 11 showed up a lot. In our office we have Safari 11.1 running on an iMac that produces the bug 100% of the time. 

Here's a test page to make it easy:
    https://stevesouders.com/tests/fid.php

On our 100% reproducible office iMac when we step through the code we get true for "if (eventTimeStamp > now)" test, but when we look at the values neither is an epoch timestamp. Instead, we get values that are very close but nevertheless eventTimeStamp is greater than now by a few ms, for example eventTimeStamp = 2078 and now = 2067.

So the test for "if (eventTimeStamp > now)" seems too broad. Instead, it should also be necessary that eventTimeStamp is greater than the minimum epoch time, navigationStart, or really any epoch time in the past. If that is true, then using +new Date works. If not, bail.

**Comment by tdresser** [comment]
Thanks for the report.
@philipwalton - can you dig in here?

**Comment by philipwalton** [comment]
It looks like this issue wasn't actually about epoch times; rather, it was becauase in Safari 11.1 there were cases where `event.timeStamp` was greater than the value of `performance.now()` when callled inside the event listener (i.e. the event was from the future).

I've created #5 to fix the problem, and in cases where the computed FID value would be negative, I clamp it at 0. It's not ideal, but I don't think there's a better option. The good news is it looks like the bug is no longer happening in Safari 12 preview.

**Comment by philipwalton** [comment]
This should be fixed in version `0.1.1`.

**Comment by stevesouders** [comment]
Super! Thanks for the fix.

FYI - We saw this issue on browsers other than Safari 11.1.

Also, with this fix people will get results saying FID=0, but really we don't know what the value should be. Certainly, it's not zero. In our code we just bail and don't report a result when this anomaly occurs because it's clear the builtin timers for the browser are unreliable.

**Comment by philipwalton** [comment]
I think it's fine to do either, and I think each has trade-offs.

From what I can tell (at least in Safari), the time mismatch between `performance.now()` and `event.timeStamp` is (or at least seems to be) constant and always a small amount. I.e. when I was seeing negative values, they were always small, but if I added a blocking while loop for a second or more, I always see large positive values.

This leads me to believe that all values are probably off by a similar (and small) amount, and any value that gets reported as zero is likely close enough to zero that it won't affect high percentiles in reporting. On the other hand, if you don't report these values at all it may skew your percentiles. I'm not sure which is best.

@tdresser let me know if you have any thoughts here...

**Comment by tdresser** [comment]
Not reporting these values seems riskier to me than reporting them as being 0, due to fear of biasing percentiles, as you mentioned.

Assuming the error is fairly tightly bounded, I agree with Philip's proposal above.

**Comment by philipwalton** [comment]
BTW, I started seeing additional bogus values, so I decided it was safer (and easier) to not report any negative values or any values greater than the delta between when the event occurred and when the event listeners were added.

This change was added in #7 and released in [0.1.2](https://github.com/GoogleChromeLabs/first-input-delay/releases/tag/0.1.2).
